# Generated by Django 3.1.3 on 2020-11-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_auto_20201118_0028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chores',
            new_name='Todo',
        ),
    ]
