# Generated by Django 3.1.3 on 2020-11-25 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_todo_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='complete',
            new_name='completed',
        ),
    ]
